
// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `
  <h1 align="center">${data.title}</h1>

  ![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />
   
  ## Table of Contents
  * [Description](#description)
  * [Installation](#installation)
  * [Usage](#usage)
  * [License](#license)
  * [Contribution](#contribution)
  * [Test](#tests)
  * [Questions?](#questions)
  
  ## Description
  ${answers.description}

  ## Installation
  ${answers.installation}

  ## Usage
  ${answers.usage}

  ## License
  ![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)
  <br />
  This application is covered by the ${answers.license} license. 

  ## Contribution
  ${answers.contribution}

  ## Test
  ${answers.tests}

  ## Questions?
  ${answers.questions}
  <br/>
  You can Email me at: ${answers.email}
  <br/>
  You can contact me on Github at: [${answers.username}](https://github.com/${answers.username})

  **My ReadMe was generated by [readme-generator](https://github.com/cocobeware83/readme-generator)

  `;
}

module.exports = generateMarkdown;
